version: 0.2

phases: 
  pre_build:
    commands:
      - echo Deployment started on `date`
      - echo Syncing S3 Content
      # REPLACE yourwebsite.com WITH THE NAME OF YOUR S3 BUCKET THAT HOSTS YOUR APP'S STATIC WEBSITE
      - aws s3 sync ./public/ s3://hombrew.dev
  build:
    commands:
      - echo Invalidating CloudFront Cache
      - aws cloudfront create-invalidation --distribution-id E14XX0FKHLRXZN --paths "/*"
  post_build:
    commands:
      - echo Deployment completed on `date`